# Generated by Django 3.1.2 on 2020-10-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('from_email', models.EmailField(max_length=50)),
                ('message', models.CharField(help_text='Write here your message!', max_length=500)),
            ],
        ),
    ]
