# Generated by Django 3.1.2 on 2020-10-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
